### PR TITLE
fix: update sol domains

### PR DESCRIPTION
**Pull request by irisdv**

### CODE REVIEW

**Review by fricoben — CHANGES_REQUESTED** [review]
Doesn't work on maynnet atm we need to deploy it and delegate .sol domain to it.

**Review by fricoben — CHANGES_REQUESTED** [review]
Works for me on Sepolia, I would just add a few front-end stuff: 
- [x] Index .sol.stark domain to be able to see them on `/identities`
- [x] After launching the TX modal is closed we can redirect the user to the identity page

**Review by fricoben — CHANGES_REQUESTED** [review]
I don't really understand what you're doing in this PR, could you explain ?

Capture d’écran 2024-04-09 à 10 30 46

Moreover I still don't see my sol domains in the `/identities` page

**Comment by irisdv** [comment]
> I don't really understand what you're doing in this PR, could you explain ?

I don't understand your question.

About the identities page, could you redo the whole process ? The indexer had the wrong field, so it won't show your sol domain in the identities page unless you redo it.

**Comment by fricoben** [comment]
> > I don't really understand what you're doing in this PR, could you explain ?
> 
> I don't understand your question.
> 
> About the identities page, could you redo the whole process? The indexer had the wrong field, so it won't show your sol domain in the identities page unless you redo it.

After testing everything again, it works but I don't have the domain in the main domain. (transaction here https://sepolia.starkscan.co/tx/0x542c15b58cd2871aa40b20c222b0ace08dde97b47d0d77afe1ea63c8e3fe181)

Capture d’écran 2024-04-09 à 10 50 56

**Review by fricoben — APPROVED** [review]
Lgtm, the last thing before merging would be to change the image to a Solana one like we do for Argent and Braavos. 

I asked them for their logo and will give you the logo soon.

**Pull request merged**
