### PR TITLE
ref: change home page

### LINKED ISSUE #120: fix: set_as_main_domain automatically called
st_as_main_domain is sometimes called even though you already have something set as main domain. It forbids you to mint a domain targeting another address than yours.

### LINKED ISSUE #125: Make domains page the default page
After the feedback that I have people understand more the concept of domains + it could help to increase the conversion rate

### PR DESCRIPTION
**Pull request by fricoben**
close #125 

It's also supposed to close #120

UPDATE on 11/02: 

I added some refactors to the function hooks in order to be cleaner but I also fixed the multicall of this issue #120

### CODE REVIEW

**Review by Th0rgal — CHANGES_REQUESTED** [review]
address ?? "" is not necessary, address should be enough for useDisplayname which supports undefined

**Comment by fricoben** [comment]
> address ?? "" is not necessary, address should be enough for useDisplayname which supports undefined

It is actually, it triggers an error on the console if I send it with undefined.

**Comment by fricoben** [comment]
> > address ?? "" is not necessary, address should be enough for useDisplayname which supports undefined
> 
> It is actually, it triggers an error on the console if I send it with undefined.

I added a lot more changes to get rid of all the `?? ""` that are dirty af

**Review by Th0rgal — APPROVED** [review]
lgtm

**Pull request merged**
