### PR TITLE
feat: mobile screen redesign 1

### LINKED ISSUE #561: Mobile screen redesign : Menu
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2378%3A39357&mode=design&t=S5K4pjgI3RFYPVn7-1

Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

### LINKED ISSUE #564: Mobile screen redesign : Identities app
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2389%3A15695&mode=design&t=S5K4pjgI3RFYPVn7-1

Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

### LINKED ISSUE #565: Mobile screen redesign : Suggestions
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2393%3A19414&mode=design&t=S5K4pjgI3RFYPVn7-1

Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

### LINKED ISSUE #566: Mobile screen redesign : NFT's view
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2393%3A19636&mode=design&t=S5K4pjgI3RFYPVn7-1

Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

### LINKED ISSUE #567: Mobile screen redesign : Popup & cookies view
Figma file : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/Starknet-ID?type=design&node-id=2393%3A21889&mode=design&t=S5K4pjgI3RFYPVn7-1

Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

### LINKED ISSUE #568: Mobile screen redesign
Loom : https://www.loom.com/share/6f5dfd82297c4332a184de1a86ea9a20

Menu : https://github.com/starknet-id/app.starknet.id/issues/561

Website : https://github.com/starknet-id/app.starknet.id/issues/562

Affiliate : https://github.com/starknet-id/app.starknet.id/issues/563

Identities app : https://github.com/starknet-id/app.starknet.id/issues/564

Suggestions : https://github.com/starknet-id/app.starknet.id/issues/565

NFT's view : https://github.com/starknet-id/app.starknet.id/issues/566

Popup & cookies view : https://github.com/starknet-id/app.starknet.id/issues/567

### PR DESCRIPTION
**Pull request by Marchand-Nicolas**
close: #561
close: #564 
close: #565 
close: #566 
close: #567 
close: #568

### CODE REVIEW

**Review by fricoben — APPROVED** [review]
code good for me, waiting for @Kevils review to merge

**Review by Kevils — CHANGES_REQUESTED** [review]
1 - The mobile menu for affiliation has not changed
image

image

2 - I think the affiliate page has not changed also: 
Delete leaves
Centered text
Color text
New text sizes
New margin, padding...etc

Link of figma : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2389%3A14617&mode=design&t=J2wPdxZypDqgMrot-1)

image

3- Same for website : 
Add image
Delete leaves
Centered text
Color text
New text sizes
New margin, padding...etc

Figma link : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=2380%3A11988&mode=design&t=J2wPdxZypDqgMrot-1

image

**Comment by Marchand-Nicolas** [comment]
> 1 - The mobile menu for affiliation has not changed...

I have done this on a separate PR, as this is not the same repo (app.starknet.id vs starknet.id)
You can check it here: https://github.com/starknet-id/starknet.id/pull/50
(Sorry I should have written that in the PR description)

**Comment by Kevils** [comment]
> > 1 - The mobile menu for affiliation has not changed...
> 
> I have done this on a separate PR, as this is not the same repo (app.starknet.id vs starknet.id) You can check it here: [starknet-id/starknet.id#50](https://github.com/starknet-id/starknet.id/pull/50) (Sorry I should have written that in the PR description)

Alright, thanks ! I approve this PR

**Review by Kevils — APPROVED** [review]
Looks good

**Pull request merged**
